import type {
  EnvMonContext,
  EnvMonSiteSummary,
  EnvMonZone,
  EnvMonAlert,
  EnvMonSwabResult,
  EnvMonTrend,
  EnvMonHeatmapCell,
  EnvMonCorrectiveAction,
  EnvMonSwabVector,
} from '@connectio/data-contracts'

export const mockEnvMonContext: EnvMonContext = {
  regionId: 'EU-WEST',
  plantId: 'IE10',
  plantName: 'Kerry Listowel',
  monitoringPeriodStart: '2024-03-01',
  monitoringPeriodEnd: '2024-03-08',
  totalZones: 24,
  activeAlerts: 3,
  openCorrectiveActions: 2,
  overallRiskStatus: 'elevated',
  lastSampleDate: '2024-03-07',
  lastUpdatedAt: '2024-03-08T15:00:00.000Z',
}

export const mockEnvMonSiteSummary: EnvMonSiteSummary = {
  plantId: 'IE10',
  plantName: 'Kerry Listowel',
  zonesMonitored: 24,
  zonesWithAlerts: 3,
  positiveCount: 5,
  positiveRate: 4.2,
  openCorrectiveActions: 2,
  overdueActions: 0,
  complianceRate: 97.5,
  riskStatus: 'elevated',
  highestSeverity: 'high',
  confidence: 0.92,
}

export const mockEnvMonZones: EnvMonZone[] = [
  {
    zoneId: 'ZONE-001',
    zoneName: 'Filling Line A',
    plantId: 'IE10',
    areaType: 'production',
    hygieneZone: 'zone-2',
    status: 'compliant',
    lastSampleDate: '2024-03-05',
    nextScheduledSample: '2024-03-12',
    consecutivePositives: 0,
    openAlerts: 0,
  },
  {
    zoneId: 'ZONE-002',
    zoneName: 'Filling Line B',
    plantId: 'IE10',
    areaType: 'production',
    hygieneZone: 'zone-2',
    status: 'compliant',
    lastSampleDate: '2024-03-06',
    nextScheduledSample: '2024-03-13',
    consecutivePositives: 0,
    openAlerts: 0,
  },
  {
    zoneId: 'ZONE-003',
    zoneName: 'Packaging Hall',
    plantId: 'IE10',
    areaType: 'packaging',
    hygieneZone: 'zone-3',
    status: 'alert',
    lastSampleDate: '2024-03-07',
    nextScheduledSample: '2024-03-08',
    consecutivePositives: 2,
    openAlerts: 2,
  },
  {
    zoneId: 'ZONE-004',
    zoneName: 'Cold Storage A',
    plantId: 'IE10',
    areaType: 'storage',
    hygieneZone: 'zone-4',
    status: 'compliant',
    lastSampleDate: '2024-03-04',
    nextScheduledSample: '2024-03-11',
    consecutivePositives: 0,
    openAlerts: 0,
  },
  {
    zoneId: 'ZONE-005',
    zoneName: 'Ingredient Dispensing',
    plantId: 'IE10',
    areaType: 'production',
    hygieneZone: 'zone-1',
    status: 'corrective-action',
    lastSampleDate: '2024-03-07',
    consecutivePositives: 1,
    openAlerts: 1,
  },
]

export const mockEnvMonAlerts: EnvMonAlert[] = [
  {
    alertId: 'ALT-001',
    zoneId: 'ZONE-003',
    zoneName: 'Packaging Hall',
    plantId: 'IE10',
    testType: 'swab',
    organism: 'Listeria monocytogenes',
    severity: 'high',
    detectedAt: '2024-03-07T09:00:00.000Z',
    status: 'corrective-action',
    correctiveActionId: 'CA-001',
    description: 'Environmental positive — Listeria monocytogenes detected in Zone 3',
    owner: 'qc.lab@listowel.ie',
  },
  {
    alertId: 'ALT-002',
    zoneId: 'ZONE-003',
    zoneName: 'Packaging Hall',
    plantId: 'IE10',
    testType: 'surface-contact',
    organism: 'Listeria spp.',
    severity: 'medium',
    detectedAt: '2024-03-06T14:30:00.000Z',
    status: 'investigating',
    description: 'Listeria spp. surface contact positive — retest scheduled',
    owner: 'qc.lab@listowel.ie',
  },
  {
    alertId: 'ALT-003',
    zoneId: 'ZONE-005',
    zoneName: 'Ingredient Dispensing',
    plantId: 'IE10',
    testType: 'swab',
    organism: 'Enterobacteriaceae',
    severity: 'medium',
    detectedAt: '2024-03-07T11:15:00.000Z',
    status: 'corrective-action',
    correctiveActionId: 'CA-002',
    description: 'Enterobacteriaceae above action level in dispensing zone',
    owner: 'qc.lab@listowel.ie',
  },
]

export const mockEnvMonSwabResults: EnvMonSwabResult[] = [
  {
    sampleId: 'SWB-2024-1023',
    zoneId: 'ZONE-003',
    zoneName: 'Packaging Hall',
    plantId: 'IE10',
    vectorId: 'VEC-001',
    testType: 'swab',
    organism: 'Listeria monocytogenes',
    result: 'positive',
    cfu: 3,
    cfuLimit: 0,
    sampleDate: '2024-03-07',
    analyst: 'M. Cronin',
    lotId: 'LOT-240307-001',
  },
  {
    sampleId: 'SWB-2024-1024',
    zoneId: 'ZONE-003',
    zoneName: 'Packaging Hall',
    plantId: 'IE10',
    vectorId: 'VEC-001',
    testType: 'surface-contact',
    organism: 'Listeria spp.',
    result: 'positive',
    cfu: 12,
    cfuLimit: 5,
    sampleDate: '2024-03-06',
    analyst: 'M. Cronin',
  },
  {
    sampleId: 'SWB-2024-1022',
    zoneId: 'ZONE-001',
    zoneName: 'Filling Line A',
    plantId: 'IE10',
    vectorId: 'VEC-002',
    testType: 'swab',
    organism: 'Total Viable Count',
    result: 'negative',
    cfu: 0,
    cfuLimit: 100,
    sampleDate: '2024-03-05',
    analyst: 'S. Murphy',
  },
  {
    sampleId: 'SWB-2024-1021',
    zoneId: 'ZONE-005',
    zoneName: 'Ingredient Dispensing',
    plantId: 'IE10',
    vectorId: 'VEC-003',
    testType: 'swab',
    organism: 'Enterobacteriaceae',
    result: 'positive',
    cfu: 45,
    cfuLimit: 10,
    sampleDate: '2024-03-07',
    analyst: 'K. Walsh',
  },
]

export const mockEnvMonTrends: EnvMonTrend[] = [
  { date: '2024-03-01', plantId: 'IE10', samplesCollected: 14, positiveCount: 0, positiveRate: 0, newAlerts: 0, resolvedAlerts: 1, openAlerts: 1, complianceRate: 100 },
  { date: '2024-03-02', plantId: 'IE10', samplesCollected: 8, positiveCount: 0, positiveRate: 0, newAlerts: 0, resolvedAlerts: 0, openAlerts: 1, complianceRate: 100 },
  { date: '2024-03-03', plantId: 'IE10', samplesCollected: 0, positiveCount: 0, positiveRate: 0, newAlerts: 0, resolvedAlerts: 1, openAlerts: 0, complianceRate: 100 },
  { date: '2024-03-04', plantId: 'IE10', samplesCollected: 10, positiveCount: 1, positiveRate: 10, newAlerts: 1, resolvedAlerts: 0, openAlerts: 1, complianceRate: 90 },
  { date: '2024-03-05', plantId: 'IE10', samplesCollected: 12, positiveCount: 0, positiveRate: 0, newAlerts: 0, resolvedAlerts: 0, openAlerts: 1, complianceRate: 100 },
  { date: '2024-03-06', plantId: 'IE10', samplesCollected: 9, positiveCount: 1, positiveRate: 11.1, newAlerts: 1, resolvedAlerts: 0, openAlerts: 2, complianceRate: 88.9 },
  { date: '2024-03-07', plantId: 'IE10', samplesCollected: 12, positiveCount: 2, positiveRate: 16.7, newAlerts: 2, resolvedAlerts: 0, openAlerts: 3, complianceRate: 83.3 },
]

export const mockEnvMonHeatmap: EnvMonHeatmapCell[] = [
  { zoneId: 'ZONE-001', zoneName: 'Filling Line A', areaType: 'production', hygieneZone: 'zone-2', riskScore: 5, positiveCount: 0, sampleCount: 12, lastTestDate: '2024-03-05', status: 'compliant' },
  { zoneId: 'ZONE-002', zoneName: 'Filling Line B', areaType: 'production', hygieneZone: 'zone-2', riskScore: 8, positiveCount: 0, sampleCount: 10, lastTestDate: '2024-03-06', status: 'compliant' },
  { zoneId: 'ZONE-003', zoneName: 'Packaging Hall', areaType: 'packaging', hygieneZone: 'zone-3', riskScore: 85, positiveCount: 3, sampleCount: 8, lastTestDate: '2024-03-07', status: 'alert' },
  { zoneId: 'ZONE-004', zoneName: 'Cold Storage A', areaType: 'storage', hygieneZone: 'zone-4', riskScore: 3, positiveCount: 0, sampleCount: 6, lastTestDate: '2024-03-04', status: 'compliant' },
  { zoneId: 'ZONE-005', zoneName: 'Ingredient Dispensing', areaType: 'production', hygieneZone: 'zone-1', riskScore: 60, positiveCount: 2, sampleCount: 9, lastTestDate: '2024-03-07', status: 'corrective-action' },
]

export const mockEnvMonCorrectiveActions: EnvMonCorrectiveAction[] = [
  {
    actionId: 'CA-001',
    alertId: 'ALT-001',
    zoneId: 'ZONE-003',
    zoneName: 'Packaging Hall',
    plantId: 'IE10',
    title: 'Deep clean and retest Zone 3 — Listeria positive',
    description: 'Full zone sanitisation per SOP-ENV-07 following Listeria monocytogenes positive environmental swab',
    actionType: 'deep-clean',
    severity: 'high',
    status: 'in-progress',
    assignee: 'hygiene.team@listowel.ie',
    dueDate: '2024-03-09',
    recurrence: false,
  },
  {
    actionId: 'CA-002',
    alertId: 'ALT-003',
    zoneId: 'ZONE-005',
    zoneName: 'Ingredient Dispensing',
    plantId: 'IE10',
    title: 'Sanitise and retest Ingredient Dispensing zone',
    description: 'Clean and retest following Enterobacteriaceae action-level exceedance',
    actionType: 'deep-clean',
    severity: 'medium',
    status: 'open',
    assignee: 'hygiene.team@listowel.ie',
    dueDate: '2024-03-10',
    recurrence: false,
  },
]

export const mockEnvMonSwabVectors: EnvMonSwabVector[] = [
  {
    vectorId: 'VEC-001',
    vectorName: 'Weekly Zone 3 + Zone 5 Route',
    plantId: 'IE10',
    zoneIds: ['ZONE-003', 'ZONE-005'],
    frequency: 'weekly',
    nextDueDate: '2024-03-14',
    lastCompletedDate: '2024-03-07',
    status: 'on-schedule',
    pointCount: 10,
    assignedTeam: 'Micro Lab',
  },
  {
    vectorId: 'VEC-002',
    vectorName: 'Bi-Weekly Production Lines Route',
    plantId: 'IE10',
    zoneIds: ['ZONE-001', 'ZONE-002'],
    frequency: 'bi-weekly',
    nextDueDate: '2024-03-12',
    lastCompletedDate: '2024-03-05',
    status: 'on-schedule',
    pointCount: 8,
    assignedTeam: 'Micro Lab',
  },
  {
    vectorId: 'VEC-003',
    vectorName: 'Monthly Cold Storage Route',
    plantId: 'IE10',
    zoneIds: ['ZONE-004'],
    frequency: 'monthly',
    nextDueDate: '2024-04-04',
    lastCompletedDate: '2024-03-04',
    status: 'on-schedule',
    pointCount: 4,
    assignedTeam: 'Micro Lab',
  },
]
