import type {
  MaintenanceReliabilityContext,
  MaintenanceKpiSummary,
  WorkOrder,
  PreventiveMaintenanceTask,
  EquipmentAvailability,
  ReliabilityMetric,
  MaintenanceBacklogItem,
} from '@connectio/data-contracts'

export const mockMaintenanceReliabilityContext: MaintenanceReliabilityContext = {
  plantId: 'IE10',
  plantName: 'Kerry Listowel',
  openWorkOrders: 14,
  overduePreventiveMaintenance: 3,
  equipmentAvailabilityPercent: 91.4,
  maintenanceBacklogHours: 47,
  lastUpdatedAt: '2026-05-14T10:00:00.000Z',
}

export const mockMaintenanceKpiSummary: MaintenanceKpiSummary = {
  plantId: 'IE10',
  openWorkOrders: 14,
  overdueWorkOrders: 2,
  criticalWorkOrders: 1,
  completedThisShift: 3,
  overduePreventiveMaintenance: 3,
  equipmentAvailabilityPercent: 91.4,
  targetAvailabilityPercent: 95,
  maintenanceBacklogHours: 47,
  confidence: 0.92,
}

export const mockWorkOrders: WorkOrder[] = [
  {
    workOrderId: 'WO-2024-01847',
    title: 'Pasteuriser PHE Gasket Replacement — Critical Leak',
    equipmentId: 'EQ-IE10-PHE-001',
    equipmentDescription: 'Plate Heat Exchanger — Pasteurisation Unit',
    lineId: 'LINE-IE10-CHEESE-01',
    workOrderType: 'emergency',
    status: 'in-progress',
    priority: 'critical',
    plannedStart: '2026-05-14T08:00:00.000Z',
    plannedFinish: '2026-05-14T12:00:00.000Z',
    actualStart: '2026-05-14T08:45:00.000Z',
    estimatedHours: 4,
    assignedTechnician: 'd.hennessy@listowel.ie',
    productionImpact: 'reduced-capacity',
  },
  {
    workOrderId: 'WO-2024-01834',
    title: 'Separator Gear Box Oil Level Low',
    equipmentId: 'EQ-IE10-SEP-002',
    equipmentDescription: 'Milk Separator — Unit 2',
    lineId: 'LINE-IE10-CHEESE-01',
    workOrderType: 'corrective',
    status: 'open',
    priority: 'high',
    plannedStart: '2026-05-14T14:00:00.000Z',
    plannedFinish: '2026-05-14T16:00:00.000Z',
    estimatedHours: 2,
    assignedTechnician: 'p.o_brien@listowel.ie',
    productionImpact: 'risk-only',
  },
  {
    workOrderId: 'WO-2024-01821',
    title: 'Conveyor Belt Tension Adjustment — Pressing Section',
    equipmentId: 'EQ-IE10-CONV-005',
    equipmentDescription: 'Cheese Press Conveyor Belt',
    workOrderType: 'preventive',
    status: 'open',
    priority: 'medium',
    plannedStart: '2026-05-15T06:00:00.000Z',
    plannedFinish: '2026-05-15T07:30:00.000Z',
    estimatedHours: 1.5,
    productionImpact: 'no-impact',
  },
  {
    workOrderId: 'WO-2024-01802',
    title: 'Cooling Tower Fan Bearing Inspection',
    equipmentId: 'EQ-IE10-CT-001',
    equipmentDescription: 'Cooling Tower — Unit 1',
    workOrderType: 'inspection',
    status: 'on-hold',
    priority: 'low',
    estimatedHours: 2,
    productionImpact: 'no-impact',
  },
  {
    workOrderId: 'WO-2024-01799',
    title: 'CIP Pump Seal Replacement — Overdue',
    equipmentId: 'EQ-IE10-CIP-003',
    equipmentDescription: 'CIP Pump — Unit 3',
    workOrderType: 'corrective',
    status: 'open',
    priority: 'high',
    plannedStart: '2026-05-13T16:00:00.000Z',
    plannedFinish: '2026-05-13T18:00:00.000Z',
    estimatedHours: 2,
    productionImpact: 'no-impact',
  },
]

export const mockPreventiveMaintenanceTasks: PreventiveMaintenanceTask[] = [
  {
    taskId: 'PM-2024-00847',
    title: 'Monthly Lubrication — Cheese Press Cylinders',
    equipmentId: 'EQ-IE10-PRESS-001',
    equipmentDescription: 'Cheese Press — Unit 1',
    frequency: 'monthly',
    dueDate: '2026-05-14T06:00:00.000Z',
    status: 'overdue',
    daysOverdue: 2,
    estimatedHours: 1,
    assignedTechnician: 'd.hennessy@listowel.ie',
  },
  {
    taskId: 'PM-2024-00839',
    title: 'Quarterly Vibration Analysis — All Pumps',
    equipmentId: 'EQ-IE10-PUMP-ALL',
    equipmentDescription: 'Process Pumps (All)',
    frequency: 'quarterly',
    dueDate: '2026-05-12T00:00:00.000Z',
    status: 'overdue',
    daysOverdue: 2,
    estimatedHours: 4,
    linkedWorkOrderId: 'WO-2024-01799',
  },
  {
    taskId: 'PM-2024-00852',
    title: 'Weekly Filter Inspection — Pasteuriser',
    equipmentId: 'EQ-IE10-PHE-001',
    equipmentDescription: 'Plate Heat Exchanger — Pasteurisation Unit',
    frequency: 'weekly',
    dueDate: '2026-05-14T12:00:00.000Z',
    status: 'due-today',
    daysOverdue: 0,
    estimatedHours: 0.5,
  },
  {
    taskId: 'PM-2024-00855',
    title: 'Daily Tank Inspection — CIP Vessels',
    equipmentId: 'EQ-IE10-CIP-ALL',
    equipmentDescription: 'CIP Vessels (All)',
    frequency: 'daily',
    dueDate: '2026-05-15T06:00:00.000Z',
    status: 'upcoming',
    daysOverdue: 0,
    estimatedHours: 0.5,
    assignedTechnician: 'p.o_brien@listowel.ie',
  },
  {
    taskId: 'PM-2024-00811',
    title: 'Annual Electrical Safety Inspection — Main Panel',
    equipmentId: 'EQ-IE10-ELEC-001',
    equipmentDescription: 'Main Electrical Distribution Panel',
    frequency: 'annually',
    dueDate: '2026-06-01T00:00:00.000Z',
    status: 'upcoming',
    daysOverdue: 0,
    estimatedHours: 8,
  },
]

export const mockEquipmentAvailability: EquipmentAvailability[] = [
  {
    equipmentId: 'EQ-IE10-PHE-001',
    equipmentDescription: 'Plate Heat Exchanger — Pasteurisation Unit',
    lineId: 'LINE-IE10-CHEESE-01',
    availabilityPercent: 88,
    targetPercent: 95,
    plannedDowntimeMinutes: 60,
    unplannedDowntimeMinutes: 135,
    currentStatus: 'maintenance',
    openWorkOrderCount: 2,
  },
  {
    equipmentId: 'EQ-IE10-SEP-002',
    equipmentDescription: 'Milk Separator — Unit 2',
    lineId: 'LINE-IE10-CHEESE-01',
    availabilityPercent: 96.5,
    targetPercent: 95,
    plannedDowntimeMinutes: 30,
    unplannedDowntimeMinutes: 15,
    currentStatus: 'running',
    openWorkOrderCount: 1,
  },
  {
    equipmentId: 'EQ-IE10-PRESS-001',
    equipmentDescription: 'Cheese Press — Unit 1',
    lineId: 'LINE-IE10-CHEESE-01',
    availabilityPercent: 97,
    targetPercent: 95,
    plannedDowntimeMinutes: 30,
    unplannedDowntimeMinutes: 0,
    currentStatus: 'running',
    openWorkOrderCount: 0,
  },
  {
    equipmentId: 'EQ-IE10-CT-001',
    equipmentDescription: 'Cooling Tower — Unit 1',
    availabilityPercent: 91,
    targetPercent: 98,
    plannedDowntimeMinutes: 0,
    unplannedDowntimeMinutes: 55,
    currentStatus: 'running',
    openWorkOrderCount: 1,
  },
]

export const mockReliabilityMetrics: ReliabilityMetric[] = [
  {
    equipmentId: 'EQ-IE10-PHE-001',
    equipmentDescription: 'Plate Heat Exchanger — Pasteurisation Unit',
    mtbfHours: 312,
    mttrHours: 3.8,
    failureCount: 2,
    oeeImpactPercent: 4.2,
    trendDirection: 'degrading',
    periodDays: 90,
  },
  {
    equipmentId: 'EQ-IE10-SEP-002',
    equipmentDescription: 'Milk Separator — Unit 2',
    mtbfHours: 720,
    mttrHours: 1.2,
    failureCount: 1,
    oeeImpactPercent: 0.8,
    trendDirection: 'stable',
    periodDays: 90,
  },
  {
    equipmentId: 'EQ-IE10-CIP-003',
    equipmentDescription: 'CIP Pump — Unit 3',
    mtbfHours: 168,
    mttrHours: 2.5,
    failureCount: 4,
    oeeImpactPercent: 1.1,
    trendDirection: 'degrading',
    periodDays: 90,
  },
]

export const mockMaintenanceBacklog: MaintenanceBacklogItem[] = [
  {
    backlogId: 'BL-2024-00142',
    title: 'Moulding Robot Arm Lubrication Service',
    equipmentId: 'EQ-IE10-ROBOT-002',
    equipmentDescription: 'Moulding Robot — Unit 2',
    deferredFrom: '2026-04-30T00:00:00.000Z',
    deferredReason: 'Production schedule — high demand period',
    estimatedHours: 3,
    priority: 'medium',
    productionImpact: 'no-impact',
    targetCompletionDate: '2026-05-21T00:00:00.000Z',
  },
  {
    backlogId: 'BL-2024-00138',
    title: 'Cooling Water System Pipe Insulation Repair',
    equipmentId: 'EQ-IE10-COOL-PIPE',
    equipmentDescription: 'Cooling Water Distribution Pipework',
    deferredFrom: '2026-04-22T00:00:00.000Z',
    deferredReason: 'Parts on order — delivery expected 2026-05-16',
    estimatedHours: 8,
    priority: 'high',
    productionImpact: 'risk-only',
    targetCompletionDate: '2026-05-18T00:00:00.000Z',
  },
  {
    backlogId: 'BL-2024-00129',
    title: 'Electrical Cabinet Thermography Survey',
    equipmentId: 'EQ-IE10-ELEC-003',
    equipmentDescription: 'Cheese Room Electrical Panels',
    deferredFrom: '2026-04-17T00:00:00.000Z',
    deferredReason: 'Specialist contractor availability',
    estimatedHours: 4,
    priority: 'medium',
    productionImpact: 'no-impact',
  },
]
