import type {
  Warehouse360OverviewContext,
  Warehouse360Summary,
  StockOverview,
  OpenHoldItem,
  GoodsMovementEvent,
  ReplenishmentNeed,
  LocationCapacity,
  NearExpiryBatch,
  WarehouseReconciliationException,
} from '@connectio/data-contracts'

export const mockWarehouse360Context: Warehouse360OverviewContext = {
  warehouseId: 'WH-IE10-MAIN',
  warehouseName: 'Kerry Listowel — Main Warehouse',
  plantId: 'IE10',
  totalStockLines: 347,
  holdPercent: 8.4,
  openTransfers: 23,
  capacityUtilizationPercent: 74.2,
  lastUpdatedAt: '2026-05-14T10:00:00.000Z',
}

export const mockWarehouse360Summary: Warehouse360Summary = {
  warehouseId: 'WH-IE10-MAIN',
  totalStockLines: 347,
  unrestrictedLines: 298,
  holdLines: 29,
  qualityInspectionLines: 20,
  openGoodsReceipts: 7,
  openGoodsIssues: 12,
  openTransfers: 23,
  capacityUtilizationPercent: 74.2,
  activeReplenishmentNeeds: 5,
  confidence: 0.95,
}

export const mockStockOverview: StockOverview = {
  warehouseId: 'WH-IE10-MAIN',
  zones: [
    {
      zoneId: 'ZONE-CHILL-A',
      zoneName: 'Chilled Zone A (0–4°C)',
      zoneType: 'chilled',
      stockLines: 142,
      capacityPercent: 81,
      holdPercent: 6.3,
    },
    {
      zoneId: 'ZONE-CHILL-B',
      zoneName: 'Chilled Zone B (0–4°C)',
      zoneType: 'chilled',
      stockLines: 98,
      capacityPercent: 67,
      holdPercent: 11.2,
    },
    {
      zoneId: 'ZONE-AMBIENT',
      zoneName: 'Ambient Zone (10–18°C)',
      zoneType: 'ambient',
      stockLines: 73,
      capacityPercent: 58,
      holdPercent: 5.5,
    },
    {
      zoneId: 'ZONE-STAGING',
      zoneName: 'Staging Lane',
      zoneType: 'staging',
      stockLines: 34,
      capacityPercent: 88,
      holdPercent: 0,
    },
  ],
  totalStorageLocations: 1240,
  occupiedLocations: 920,
  blockedLocations: 47,
}

export const mockOpenHolds: OpenHoldItem[] = [
  {
    holdId: 'HOLD-2024-00312',
    batchId: 'CH-240308-0047',
    materialId: 'MAT-CH-EMMENTAL-BLOCK',
    materialDescription: 'Emmental Block 4 kg',
    storageLocationId: 'CHILL-A-023-B04',
    holdReason: 'quality-hold',
    holdQuantity: 480,
    uom: 'KG',
    raisedAt: '2026-05-14T06:30:00.000Z',
    raisedBy: 'c.moriarty@listowel.ie',
    ageHours: 3.5,
    linkedWorkspaceId: 'quality-batch-release',
  },
  {
    holdId: 'HOLD-2024-00308',
    batchId: 'CH-240307-0041',
    materialId: 'MAT-CH-CHEDDAR-BLOCK',
    materialDescription: 'Cheddar Block 20 kg',
    storageLocationId: 'CHILL-B-011-A02',
    holdReason: 'investigation',
    holdQuantity: 2000,
    uom: 'KG',
    raisedAt: '2026-05-13T14:00:00.000Z',
    raisedBy: 'quality.ie10@kerry.com',
    ageHours: 20,
    linkedWorkspaceId: 'trace-investigation',
  },
  {
    holdId: 'HOLD-2024-00301',
    materialId: 'MAT-RM-RENNET',
    materialDescription: 'Liquid Rennet 25 L',
    storageLocationId: 'CHILL-A-007-C01',
    holdReason: 'expired',
    holdQuantity: 75,
    uom: 'L',
    raisedAt: '2026-05-12T08:00:00.000Z',
    ageHours: 50,
  },
]

export const mockGoodsMovements: GoodsMovementEvent[] = [
  {
    movementId: 'GR-2024-004812',
    timestamp: '2026-05-14T07:00:00.000Z',
    movementType: 'goods-receipt',
    materialId: 'MAT-RM-RAW-MILK',
    materialDescription: 'Raw Milk — Full Tanker',
    quantity: 25000,
    uom: 'L',
    destinationLocation: 'CHILL-A-BULK-01',
    referenceDocument: 'PO-240308-0021',
    postedBy: 'warehouse.ie10@kerry.com',
  },
  {
    movementId: 'GI-2024-003547',
    timestamp: '2026-05-14T08:30:00.000Z',
    movementType: 'goods-issue',
    materialId: 'MAT-START-CULTURE-B10',
    materialDescription: 'Starter Culture B10',
    batchId: 'SC-240308-0003',
    quantity: 2.5,
    uom: 'KG',
    sourceLocation: 'CHILL-A-007-B03',
    referenceDocument: 'PO-240308-3847',
    postedBy: 'warehouse.ie10@kerry.com',
  },
  {
    movementId: 'TO-2024-001923',
    timestamp: '2026-05-14T09:15:00.000Z',
    movementType: 'transfer-order',
    materialId: 'MAT-CH-EMMENTAL-BLOCK',
    materialDescription: 'Emmental Block 4 kg',
    batchId: 'CH-240307-0038',
    quantity: 960,
    uom: 'KG',
    sourceLocation: 'CHILL-B-002-A01',
    destinationLocation: 'STAGING-LANE-04',
    referenceDocument: 'PO-240309-4102',
    postedBy: 'warehouse.ie10@kerry.com',
  },
  {
    movementId: 'GR-2024-004799',
    timestamp: '2026-05-14T06:45:00.000Z',
    movementType: 'goods-receipt',
    materialId: 'MAT-PACK-SHRINKWRAP',
    materialDescription: 'Shrink Wrap Film Roll',
    quantity: 50,
    uom: 'ROL',
    destinationLocation: 'AMBIENT-PACK-001',
    referenceDocument: 'PO-240308-0019',
    postedBy: 'warehouse.ie10@kerry.com',
  },
  {
    movementId: 'ADJ-2024-000487',
    timestamp: '2026-05-14T05:30:00.000Z',
    movementType: 'adjustment',
    materialId: 'MAT-RM-RENNET',
    materialDescription: 'Liquid Rennet 25 L',
    quantity: -75,
    uom: 'L',
    sourceLocation: 'CHILL-A-007-C01',
    referenceDocument: 'HOLD-2024-00301',
  },
]

export const mockReplenishmentNeeds: ReplenishmentNeed[] = [
  {
    needId: 'REP-001',
    materialId: 'MAT-START-CULTURE-B10',
    materialDescription: 'Starter Culture B10',
    storageLocationId: 'CHILL-A-007-B03',
    currentStockQuantity: 3.5,
    reorderPoint: 5,
    targetQuantity: 15,
    uom: 'KG',
    urgency: 'high',
    openPurchaseOrderId: 'PO-240309-0047',
    expectedDelivery: '2026-05-15T08:00:00.000Z',
  },
  {
    needId: 'REP-002',
    materialId: 'MAT-RM-RENNET',
    materialDescription: 'Liquid Rennet 25 L',
    storageLocationId: 'CHILL-A-007-C01',
    currentStockQuantity: 0,
    reorderPoint: 50,
    targetQuantity: 150,
    uom: 'L',
    urgency: 'critical',
  },
  {
    needId: 'REP-003',
    materialId: 'MAT-PACK-SHRINKWRAP',
    materialDescription: 'Shrink Wrap Film Roll',
    storageLocationId: 'AMBIENT-PACK-001',
    currentStockQuantity: 50,
    reorderPoint: 40,
    targetQuantity: 200,
    uom: 'ROL',
    urgency: 'medium',
  },
  {
    needId: 'REP-004',
    materialId: 'MAT-PACK-LABEL-EMMENTAL',
    materialDescription: 'Emmental Block Label',
    storageLocationId: 'AMBIENT-PACK-002',
    currentStockQuantity: 1200,
    reorderPoint: 2000,
    targetQuantity: 8000,
    uom: 'EA',
    urgency: 'high',
    openPurchaseOrderId: 'PO-240310-0012',
    expectedDelivery: '2026-05-16T12:00:00.000Z',
  },
  {
    needId: 'REP-005',
    materialId: 'MAT-CIP-CAUSTIC',
    materialDescription: 'CIP Caustic Solution',
    storageLocationId: 'AMBIENT-CHEM-001',
    currentStockQuantity: 180,
    reorderPoint: 200,
    targetQuantity: 600,
    uom: 'L',
    urgency: 'medium',
  },
]

export const mockLocationCapacities: LocationCapacity[] = [
  {
    locationId: 'CHILL-A-BULK-01',
    locationName: 'Chilled A — Bulk Bay 1',
    zoneId: 'ZONE-CHILL-A',
    zoneName: 'Chilled Zone A',
    totalCapacityUnits: 40000,
    usedCapacityUnits: 25000,
    utilizationPercent: 62.5,
    locationType: 'bulk-area',
    isBlocked: false,
  },
  {
    locationId: 'STAGING-LANE-04',
    locationName: 'Staging Lane 4',
    zoneId: 'ZONE-STAGING',
    zoneName: 'Staging Lane',
    totalCapacityUnits: 4000,
    usedCapacityUnits: 3840,
    utilizationPercent: 96,
    locationType: 'staging-lane',
    isBlocked: false,
  },
  {
    locationId: 'CHILL-B-011-A02',
    locationName: 'Chilled B — 011-A02',
    zoneId: 'ZONE-CHILL-B',
    zoneName: 'Chilled Zone B',
    totalCapacityUnits: 2000,
    usedCapacityUnits: 2000,
    utilizationPercent: 100,
    locationType: 'rack',
    isBlocked: true,
    blockReason: 'Quality hold HOLD-2024-00308',
  },
  {
    locationId: 'AMBIENT-PACK-001',
    locationName: 'Ambient — Packaging Store 1',
    zoneId: 'ZONE-AMBIENT',
    zoneName: 'Ambient Zone',
    totalCapacityUnits: 500,
    usedCapacityUnits: 50,
    utilizationPercent: 10,
    locationType: 'shelf',
    isBlocked: false,
  },
]

export const mockNearExpiryBatches: NearExpiryBatch[] = [
  {
    batchId: 'SC-240308-0003',
    materialId: 'MAT-START-CULTURE-B10',
    materialDescription: 'Starter Culture B10',
    storageLocationId: 'CHILL-A-007-B03',
    expiryDate: '2026-05-17T00:00:00.000Z',
    daysUntilExpiry: 1,
    quantity: 3.5,
    uom: 'KG',
    urgency: 'critical',
    holdStatus: 'unrestricted',
  },
  {
    batchId: 'RM-240301-0021',
    materialId: 'MAT-RM-RENNET',
    materialDescription: 'Liquid Rennet 25 L',
    storageLocationId: 'CHILL-A-007-C01',
    expiryDate: '2026-05-14T00:00:00.000Z',
    daysUntilExpiry: -2,
    quantity: 75,
    uom: 'L',
    urgency: 'expired',
    holdStatus: 'quality-hold',
  },
  {
    batchId: 'CH-240225-0018',
    materialId: 'MAT-CH-CHEDDAR-BLOCK',
    materialDescription: 'Cheddar Block 20 kg',
    storageLocationId: 'CHILL-B-011-A02',
    expiryDate: '2026-05-21T00:00:00.000Z',
    daysUntilExpiry: 5,
    quantity: 400,
    uom: 'KG',
    urgency: 'warning',
    holdStatus: 'unrestricted',
  },
  {
    batchId: 'CH-240228-0033',
    materialId: 'MAT-CH-EMMENTAL-BLOCK',
    materialDescription: 'Emmental Block 4 kg',
    storageLocationId: 'CHILL-A-023-B04',
    expiryDate: '2026-05-26T00:00:00.000Z',
    daysUntilExpiry: 10,
    quantity: 120,
    uom: 'KG',
    urgency: 'caution',
    holdStatus: 'unrestricted',
  },
]

export const mockWarehouseReconciliationExceptions: WarehouseReconciliationException[] = [
  {
    exceptionId: 'RECON-2024-00047',
    exceptionType: 'quantity-mismatch',
    materialId: 'MAT-CH-EMMENTAL-BLOCK',
    materialDescription: 'Emmental Block 4 kg',
    batchId: 'CH-240308-0047',
    storageLocationId: 'CHILL-A-023-B04',
    imQuantity: 500,
    wmsQuantity: 480,
    discrepancyQuantity: 20,
    uom: 'KG',
    detectedAt: '2026-05-14T06:45:00.000Z',
    ageHours: 3.25,
    severity: 'high',
    resolution: 'open',
  },
  {
    exceptionId: 'RECON-2024-00046',
    exceptionType: 'missing-in-wms',
    materialId: 'MAT-START-CULTURE-B10',
    materialDescription: 'Starter Culture B10',
    batchId: 'SC-240307-0002',
    storageLocationId: 'CHILL-A-007-B03',
    imQuantity: 2.0,
    uom: 'KG',
    detectedAt: '2026-05-13T22:00:00.000Z',
    ageHours: 12,
    severity: 'medium',
    resolution: 'in-progress',
  },
  {
    exceptionId: 'RECON-2024-00044',
    exceptionType: 'location-mismatch',
    materialId: 'MAT-CH-CHEDDAR-BLOCK',
    materialDescription: 'Cheddar Block 20 kg',
    batchId: 'CH-240307-0041',
    storageLocationId: 'CHILL-B-011-A02',
    imQuantity: 2000,
    wmsQuantity: 2000,
    discrepancyQuantity: 0,
    uom: 'KG',
    detectedAt: '2026-05-13T14:30:00.000Z',
    ageHours: 19.5,
    severity: 'low',
    resolution: 'open',
  },
]
