import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    include: ['src/**/*.test.tsx', 'src/**/*.test.ts'],
    setupFiles: ['src/test-setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/index.ts',
        'src/test-setup.ts',
        'src/TraceabilityWorkspace.tsx',
        'src/registration.ts',
        'src/trace-investigation-registration.ts',
        'src/trace-investigation-workspace.tsx',
        'src/traceabilityClient.ts',
        'src/actions/**',
        'src/adapters/trace2-adapter-factory.ts',
        'src/adapters/trace2-queries.ts',
        'src/panels/BatchLineagePanel.tsx',
        'src/panels/TraceExposureSummaryPanel.tsx',
        'src/panels/batch-header-panel.tsx',
        'src/panels/coa-release-status-panel.tsx',
        'src/panels/customer-impact-panel.tsx',
        'src/panels/event-timeline-panel.tsx',
        'src/panels/material-supplier-exposure-panel.tsx',
        'src/panels/related-investigations-panel.tsx',
        'src/panels/risk-signals-panel.tsx',
        'src/panels/trace-exposure-for-release-panel.tsx',
        'src/views/customer-exposure-view.tsx',
        'src/views/mass-balance-view.tsx',
        'src/views/recall-readiness-view.tsx',
        'src/views/supplier-exposure-view.tsx',
        'src/views/timeline-events-view.tsx',
      ],
      thresholds: { lines: 60, functions: 60, branches: 60, statements: 60 },
    },
  },
})
