// Phase 6 snapshot — simulation data accurate as of 2026-05-15. Results are read-only.
import { useState } from 'react'
import { StaticSnapshotBanner } from '../components/StaticSnapshotBanner.js'
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  Badge,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Button,
  Separator,
} from '@connectio/design-system'
import type { CutoverSimulationMode, CutoverSimulationResult, ReadinessFinding } from '@connectio/product-model'

// ─── Simulation configuration ─────────────────────────────────────────────────

interface SimulationPair {
  readonly pairId: string
  readonly workspaceIds: readonly string[]
  readonly legacySystemId: string
  readonly legacySystemName: string
  readonly currentMode: CutoverSimulationMode
  readonly pilotSite: string
  readonly description: string
}

const SIMULATION_PAIRS: readonly SimulationPair[] = [
  {
    pairId: 'trace-intelex',
    workspaceIds: ['trace-investigation'],
    legacySystemId: 'intelex-trace',
    legacySystemName: 'Intelex Traceability Platform',
    currentMode: 'simulate-redirect',
    pilotSite: 'IE10 (Kerry Listowel)',
    description: 'ConnectIO Trace Investigation handling all traceability deep links. Intelex is in read-only mode at pilot site.',
  },
  {
    pairId: 'quality-labware',
    workspaceIds: ['quality-batch-release', 'spc-monitoring'],
    legacySystemId: 'labware-lims',
    legacySystemName: 'LabWare LIMS',
    currentMode: 'observe',
    pilotSite: 'IE10 (Kerry Listowel)',
    description: 'Both systems running in parallel. Quality team validating ConnectIO release decisions against LabWare outcomes.',
  },
  {
    pairId: 'operations-phasemanager',
    workspaceIds: ['operations-plan-risk', 'process-order-review'],
    legacySystemId: 'rockwell-phasemanager',
    legacySystemName: 'Rockwell PhaseManager MES',
    currentMode: 'observe',
    pilotSite: 'IE10 (Kerry Listowel)',
    description: 'PhaseManager remains primary. ConnectIO used for risk overlay and order review only. Phase gate approval gap blocks full simulation.',
  },
  {
    pairId: 'em-excel',
    workspaceIds: ['environmental-monitoring'],
    legacySystemId: 'em-excel-sharepoint',
    legacySystemName: 'Excel/SharePoint EM Tracker',
    currentMode: 'simulate-retirement',
    pilotSite: 'IE10 (Kerry Listowel)',
    description: 'ConnectIO Environmental Monitoring has fully superseded the Excel tracker at IE10. Tracker is archived.',
  },
  {
    pairId: 'staging-wms',
    workspaceIds: ['production-staging', 'warehouse-360-overview'],
    legacySystemId: 'manhattan-wms',
    legacySystemName: 'Manhattan SCALE WMS',
    currentMode: 'off',
    pilotSite: 'Not yet started',
    description: 'Cutover simulation not started. EWM adapter design complete; awaiting pilot site commitment from logistics team.',
  },
  {
    pairId: 'maintenance-sap-pm',
    workspaceIds: ['maintenance-reliability'],
    legacySystemId: 'sap-pm',
    legacySystemName: 'SAP Plant Maintenance',
    currentMode: 'off',
    pilotSite: 'Not yet started',
    description: 'SAP PM API contract not yet finalised. Simulation cannot start until adapter implementation begins.',
  },
]

// ─── Static simulation results ────────────────────────────────────────────────

const SIMULATION_RESULTS: readonly CutoverSimulationResult[] = [
  {
    simulationId: 'sim-trace-001',
    workspaceId: 'trace-investigation',
    legacySystemId: 'intelex-trace',
    mode: 'simulate-redirect',
    startedAt: '2026-04-01T08:00:00.000Z',
    endedAt: undefined,
    passed: true,
    notes: 'All Intelex deep links from LIMS and MES are successfully intercepting and redirecting to Trace Investigation. No user-reported navigation failures in 6 weeks.',
    findings: [],
  },
  {
    simulationId: 'sim-quality-001',
    workspaceId: 'quality-batch-release',
    legacySystemId: 'labware-lims',
    mode: 'observe',
    startedAt: '2026-03-15T08:00:00.000Z',
    endedAt: undefined,
    passed: true,
    notes: 'Parallel operation running successfully. 47 batches released through ConnectIO with LabWare as shadow. 3 minor discrepancies found, all resolved.',
    findings: [
      {
        findingId: 'sim-qbr-finding-001',
        itemType: 'simulation',
        itemId: 'quality-batch-release',
        title: 'Certificate of Analysis not generated by ConnectIO',
        description: 'In 3 cases, users completed batch release in ConnectIO but still needed LabWare to generate the CoA PDF. CoA generation is out-of-scope for Phase 6.',
        severity: 'warning',
        readinessStatus: 'ready-with-warnings',
        ownerDomain: 'quality',
        lifecycle: 'live',
        recommendation: 'Document the parallel CoA step as a known workaround until Phase 7 document management integration.',
        blocksPilot: false,
        blocksProduction: false,
        createdAt: '2026-05-01T09:00:00.000Z',
        source: 'simulation',
      },
    ] as ReadinessFinding[],
  },
  {
    simulationId: 'sim-em-001',
    workspaceId: 'environmental-monitoring',
    legacySystemId: 'em-excel-sharepoint',
    mode: 'simulate-retirement',
    startedAt: '2026-02-01T08:00:00.000Z',
    endedAt: '2026-04-30T17:00:00.000Z',
    passed: true,
    notes: 'Excel tracker retired successfully at IE10. No regressions reported. All historical data archived to SharePoint read-only. Full retirement achieved.',
    findings: [],
  },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

function modeVariant(mode: CutoverSimulationMode): 'default' | 'secondary' | 'destructive' | 'outline' {
  switch (mode) {
    case 'simulate-retirement': return 'default'
    case 'simulate-redirect': return 'secondary'
    case 'observe': return 'outline'
    case 'off': return 'destructive'
  }
}

function modeLabel(mode: CutoverSimulationMode): string {
  switch (mode) {
    case 'simulate-retirement': return 'Simulating Retirement'
    case 'simulate-redirect': return 'Redirecting'
    case 'observe': return 'Observe'
    case 'off': return 'Off'
  }
}

function modeDescription(mode: CutoverSimulationMode): string {
  switch (mode) {
    case 'simulate-retirement':
      return 'Legacy system is disabled; all traffic routes to ConnectIO.'
    case 'simulate-redirect':
      return 'Deep links from legacy system are intercepted and redirected to ConnectIO.'
    case 'observe':
      return 'Both systems run in parallel. Teams validate ConnectIO against legacy outcomes.'
    case 'off':
      return 'Simulation not yet started.'
  }
}

// ─── Sub-views ────────────────────────────────────────────────────────────────

function SimulationStatusKpi() {
  const counts = {
    retirement: SIMULATION_PAIRS.filter(p => p.currentMode === 'simulate-retirement').length,
    redirect: SIMULATION_PAIRS.filter(p => p.currentMode === 'simulate-redirect').length,
    observe: SIMULATION_PAIRS.filter(p => p.currentMode === 'observe').length,
    off: SIMULATION_PAIRS.filter(p => p.currentMode === 'off').length,
  }
  return (
    <div style={{ display: 'flex', gap: 12, marginBottom: 24, flexWrap: 'wrap' }}>
      {[
        { label: 'Retired', value: counts.retirement, variant: 'default' as const },
        { label: 'Redirecting', value: counts.redirect, variant: 'secondary' as const },
        { label: 'Observing', value: counts.observe, variant: 'outline' as const },
        { label: 'Not Started', value: counts.off, variant: 'destructive' as const },
      ].map(({ label, value }) => (
        <Card key={label} style={{ minWidth: 120 }}>
          <CardContent style={{ padding: '12px 16px' }}>
            <div style={{ fontSize: 11, color: 'var(--shell-fg-3)', marginBottom: 4, textTransform: 'uppercase', letterSpacing: '0.06em' }}>
              {label}
            </div>
            <span style={{ fontSize: 28, fontWeight: 700 }}>{value}</span>
          </CardContent>
        </Card>
      ))}
    </div>
  )
}

function PairCard({ pair }: { readonly pair: SimulationPair }) {
  const result = SIMULATION_RESULTS.find(r => r.workspaceId === pair.workspaceIds[0] && r.mode === pair.currentMode)
  return (
    <Card>
      <CardHeader style={{ paddingBottom: 8 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 }}>
          <div>
            <CardTitle style={{ fontSize: 14 }}>{pair.legacySystemName}</CardTitle>
            <CardDescription style={{ fontSize: 11 }}>
              Superseded by: {pair.workspaceIds.join(', ')} · Site: {pair.pilotSite}
            </CardDescription>
          </div>
          <Badge variant={modeVariant(pair.currentMode)}>{modeLabel(pair.currentMode)}</Badge>
        </div>
      </CardHeader>
      <CardContent style={{ paddingTop: 0 }}>
        <div style={{ fontSize: 12, color: 'var(--shell-fg-2)', marginBottom: 8 }}>
          {pair.description}
        </div>
        <div style={{ fontSize: 11, color: 'var(--shell-fg-3)', fontStyle: 'italic', marginBottom: result ? 10 : 0 }}>
          Mode: {modeDescription(pair.currentMode)}
        </div>
        {result && (
          <>
            <Separator style={{ margin: '10px 0' }} />
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
              <Badge variant={result.passed ? 'default' : 'destructive'}>
                {result.passed ? 'Simulation Passing' : 'Issues Found'}
              </Badge>
              <span style={{ fontSize: 11, color: 'var(--shell-fg-3)' }}>
                Started: {result.startedAt.slice(0, 10)}
                {result.endedAt ? ` · Ended: ${result.endedAt.slice(0, 10)}` : ' · Ongoing'}
              </span>
            </div>
            <div style={{ fontSize: 12, color: 'var(--shell-fg-2)', marginBottom: result.findings.length ? 8 : 0 }}>
              {result.notes}
            </div>
            {result.findings.length > 0 && result.findings.map(f => (
              <div key={f.findingId} style={{
                padding: '6px 10px',
                background: 'var(--shell-bg)',
                borderRadius: 4,
                borderLeft: '3px solid #D97706',
                marginTop: 6,
                fontSize: 11,
                color: 'var(--shell-fg-2)',
              }}>
                <strong style={{ color: 'var(--shell-fg)' }}>{f.title}</strong><br />
                {f.description}
              </div>
            ))}
          </>
        )}
      </CardContent>
    </Card>
  )
}

function ConfigurationView() {
  const [selectedMode, setSelectedMode] = useState<CutoverSimulationMode | 'all'>('all')

  const modes: Array<{ value: CutoverSimulationMode | 'all'; label: string }> = [
    { value: 'all', label: 'All' },
    { value: 'simulate-retirement', label: 'Retired' },
    { value: 'simulate-redirect', label: 'Redirecting' },
    { value: 'observe', label: 'Observe' },
    { value: 'off', label: 'Not Started' },
  ]

  const filtered = selectedMode === 'all' ? SIMULATION_PAIRS : SIMULATION_PAIRS.filter(p => p.currentMode === selectedMode)

  return (
    <div>
      <div style={{ display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap' }}>
        {modes.map(m => (
          <Button
            key={m.value}
            variant={selectedMode === m.value ? 'default' : 'outline'}
            size="sm"
            onClick={() => setSelectedMode(m.value)}
          >
            {m.label}
          </Button>
        ))}
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {filtered.map(pair => <PairCard key={pair.pairId} pair={pair} />)}
      </div>
    </div>
  )
}

function ResultsView() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
      {SIMULATION_RESULTS.length === 0 && (
        <div style={{ padding: '32px 0', textAlign: 'center', color: 'var(--shell-fg-3)', fontSize: 13 }}>
          No simulation results recorded yet.
        </div>
      )}
      {SIMULATION_RESULTS.map(r => (
        <Card key={r.simulationId}>
          <CardHeader style={{ paddingBottom: 8 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <CardTitle style={{ fontSize: 13 }}>{r.workspaceId} ↔ {r.legacySystemId}</CardTitle>
              <div style={{ display: 'flex', gap: 6 }}>
                <Badge variant={modeVariant(r.mode)}>{modeLabel(r.mode)}</Badge>
                <Badge variant={r.passed ? 'default' : 'destructive'}>{r.passed ? 'Passed' : 'Failed'}</Badge>
              </div>
            </div>
          </CardHeader>
          <CardContent style={{ paddingTop: 0 }}>
            <div style={{ fontSize: 12, color: 'var(--shell-fg-2)', marginBottom: 6 }}>{r.notes}</div>
            <div style={{ fontSize: 11, color: 'var(--shell-fg-3)' }}>
              {r.startedAt.slice(0, 10)} → {r.endedAt ? r.endedAt.slice(0, 10) : 'ongoing'} ·{' '}
              {r.findings.length} finding{r.findings.length !== 1 ? 's' : ''}
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────

type SimTab = 'configuration' | 'results'

export function CutoverSimulationPage() {
  const [activeTab, setActiveTab] = useState<SimTab>('configuration')

  return (
    <div style={{ padding: 24, maxWidth: 900 }}>
      <StaticSnapshotBanner snapshotDate="2026-05-15" />
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontSize: 22, fontWeight: 700, color: 'var(--shell-fg)', margin: 0, marginBottom: 4 }}>
          Cutover Simulation
        </h1>
        <p style={{ fontSize: 13, color: 'var(--shell-fg-2)', margin: 0 }}>
          Per-legacy-system cutover simulation mode and live results.
          Modes progress from <em>off → observe → simulate-redirect → simulate-retirement</em>.
          Phase 6 snapshot (2026-05-15) — mode changes are applied by the platform team as pilot milestones are met.
        </p>
      </div>

      <SimulationStatusKpi />

      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as SimTab)}>
        <TabsList style={{ marginBottom: 16 }}>
          <TabsTrigger value="configuration">Simulation Pairs ({SIMULATION_PAIRS.length})</TabsTrigger>
          <TabsTrigger value="results">Results ({SIMULATION_RESULTS.length})</TabsTrigger>
        </TabsList>
        <TabsContent value="configuration">
          <ConfigurationView />
        </TabsContent>
        <TabsContent value="results">
          <ResultsView />
        </TabsContent>
      </Tabs>
    </div>
  )
}
